// Code generated by Kitex v1.15.3. DO NOT EDIT.

package agentchatservice

import (
	chat "agnet-project-demo/backend/kitex_gen/chat"
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newAgentChatServiceLoginArgs,
		newAgentChatServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newAgentChatServiceChatArgs,
		newAgentChatServiceChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChatStream": kitex.NewMethodInfo(
		chatStreamHandler,
		newAgentChatServiceChatStreamArgs,
		newAgentChatServiceChatStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"CreateSession": kitex.NewMethodInfo(
		createSessionHandler,
		newAgentChatServiceCreateSessionArgs,
		newAgentChatServiceCreateSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSessions": kitex.NewMethodInfo(
		listSessionsHandler,
		newAgentChatServiceListSessionsArgs,
		newAgentChatServiceListSessionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSession": kitex.NewMethodInfo(
		getSessionHandler,
		newAgentChatServiceGetSessionArgs,
		newAgentChatServiceGetSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetIMChatSummary": kitex.NewMethodInfo(
		getIMChatSummaryHandler,
		newAgentChatServiceGetIMChatSummaryArgs,
		newAgentChatServiceGetIMChatSummaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentChatServiceServiceInfo                = NewServiceInfo()
	agentChatServiceServiceInfoForClient       = NewServiceInfoForClient()
	agentChatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentChatServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentChatServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentChatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentChatService"
	handlerType := (*chat.AgentChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.15.3",
		Extra:           extra,
	}
	return svcInfo
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.AgentChatServiceLoginArgs)
	realResult := result.(*chat.AgentChatServiceLoginResult)
	success, err := handler.(chat.AgentChatService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentChatServiceLoginArgs() interface{} {
	return chat.NewAgentChatServiceLoginArgs()
}

func newAgentChatServiceLoginResult() interface{} {
	return chat.NewAgentChatServiceLoginResult()
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.AgentChatServiceChatArgs)
	realResult := result.(*chat.AgentChatServiceChatResult)
	success, err := handler.(chat.AgentChatService).Chat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentChatServiceChatArgs() interface{} {
	return chat.NewAgentChatServiceChatArgs()
}

func newAgentChatServiceChatResult() interface{} {
	return chat.NewAgentChatServiceChatResult()
}

func chatStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, err := streaming.GetServerStreamFromArg(arg)
	if err != nil {
		return err
	}
	stream := streaming.NewServerStreamingServer[chat.ChatStreamChunk](st)
	req := new(chat.ChatRequest)
	if err := st.RecvMsg(ctx, req); err != nil {
		return err
	}
	return handler.(chat.AgentChatService).ChatStream(ctx, req, stream)
}

type agentChatServiceChatStreamClient struct {
	streaming.Stream
}

func (x *agentChatServiceChatStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *agentChatServiceChatStreamClient) Recv() (*chat.ChatStreamChunk, error) {
	m := new(chat.ChatStreamChunk)
	return m, x.Stream.RecvMsg(m)
}

type agentChatServiceChatStreamServer struct {
	streaming.Stream
}

func (x *agentChatServiceChatStreamServer) Send(m *chat.ChatStreamChunk) error {
	return x.Stream.SendMsg(m)
}

func newAgentChatServiceChatStreamArgs() interface{} {
	return chat.NewAgentChatServiceChatStreamArgs()
}

func newAgentChatServiceChatStreamResult() interface{} {
	return chat.NewAgentChatServiceChatStreamResult()
}

func createSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.AgentChatServiceCreateSessionArgs)
	realResult := result.(*chat.AgentChatServiceCreateSessionResult)
	success, err := handler.(chat.AgentChatService).CreateSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentChatServiceCreateSessionArgs() interface{} {
	return chat.NewAgentChatServiceCreateSessionArgs()
}

func newAgentChatServiceCreateSessionResult() interface{} {
	return chat.NewAgentChatServiceCreateSessionResult()
}

func listSessionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.AgentChatServiceListSessionsArgs)
	realResult := result.(*chat.AgentChatServiceListSessionsResult)
	success, err := handler.(chat.AgentChatService).ListSessions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentChatServiceListSessionsArgs() interface{} {
	return chat.NewAgentChatServiceListSessionsArgs()
}

func newAgentChatServiceListSessionsResult() interface{} {
	return chat.NewAgentChatServiceListSessionsResult()
}

func getSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.AgentChatServiceGetSessionArgs)
	realResult := result.(*chat.AgentChatServiceGetSessionResult)
	success, err := handler.(chat.AgentChatService).GetSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentChatServiceGetSessionArgs() interface{} {
	return chat.NewAgentChatServiceGetSessionArgs()
}

func newAgentChatServiceGetSessionResult() interface{} {
	return chat.NewAgentChatServiceGetSessionResult()
}

func getIMChatSummaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.AgentChatServiceGetIMChatSummaryArgs)
	realResult := result.(*chat.AgentChatServiceGetIMChatSummaryResult)
	success, err := handler.(chat.AgentChatService).GetIMChatSummary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentChatServiceGetIMChatSummaryArgs() interface{} {
	return chat.NewAgentChatServiceGetIMChatSummaryArgs()
}

func newAgentChatServiceGetIMChatSummaryResult() interface{} {
	return chat.NewAgentChatServiceGetIMChatSummaryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Login(ctx context.Context, req *chat.LoginRequest) (r *chat.LoginResponse, err error) {
	var _args chat.AgentChatServiceLoginArgs
	_args.Req = req
	var _result chat.AgentChatServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Chat(ctx context.Context, req *chat.ChatRequest) (r *chat.ChatResponse, err error) {
	var _args chat.AgentChatServiceChatArgs
	_args.Req = req
	var _result chat.AgentChatServiceChatResult
	if err = p.c.Call(ctx, "Chat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChatStream(ctx context.Context, req *chat.ChatRequest) (AgentChatService_ChatStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "ChatStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &agentChatServiceChatStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) CreateSession(ctx context.Context, req *chat.CreateSessionRequest) (r *chat.CreateSessionResponse, err error) {
	var _args chat.AgentChatServiceCreateSessionArgs
	_args.Req = req
	var _result chat.AgentChatServiceCreateSessionResult
	if err = p.c.Call(ctx, "CreateSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSessions(ctx context.Context, req *chat.ListSessionsRequest) (r *chat.ListSessionsResponse, err error) {
	var _args chat.AgentChatServiceListSessionsArgs
	_args.Req = req
	var _result chat.AgentChatServiceListSessionsResult
	if err = p.c.Call(ctx, "ListSessions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSession(ctx context.Context, req *chat.GetSessionRequest) (r *chat.GetSessionResponse, err error) {
	var _args chat.AgentChatServiceGetSessionArgs
	_args.Req = req
	var _result chat.AgentChatServiceGetSessionResult
	if err = p.c.Call(ctx, "GetSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetIMChatSummary(ctx context.Context, req *chat.IMChatSummaryRequest) (r *chat.IMChatSummaryResponse, err error) {
	var _args chat.AgentChatServiceGetIMChatSummaryArgs
	_args.Req = req
	var _result chat.AgentChatServiceGetIMChatSummaryResult
	if err = p.c.Call(ctx, "GetIMChatSummary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
