// Code generated by Kitex v1.15.3. DO NOT EDIT.

package agentchatservice

import (
	chat "agnet-project-demo/backend/kitex_gen/chat"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/client/callopt/streamcall"
	"github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *chat.LoginRequest, callOptions ...callopt.Option) (r *chat.LoginResponse, err error)
	Chat(ctx context.Context, req *chat.ChatRequest, callOptions ...callopt.Option) (r *chat.ChatResponse, err error)
	CreateSession(ctx context.Context, req *chat.CreateSessionRequest, callOptions ...callopt.Option) (r *chat.CreateSessionResponse, err error)
	ListSessions(ctx context.Context, req *chat.ListSessionsRequest, callOptions ...callopt.Option) (r *chat.ListSessionsResponse, err error)
	GetSession(ctx context.Context, req *chat.GetSessionRequest, callOptions ...callopt.Option) (r *chat.GetSessionResponse, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	ChatStream(ctx context.Context, req *chat.ChatRequest, callOptions ...streamcall.Option) (stream AgentChatService_ChatStreamClient, err error)
}

type AgentChatService_ChatStreamClient interface {
	streaming.Stream
	Recv() (*chat.ChatStreamChunk, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAgentChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAgentChatServiceClient struct {
	*kClient
}

func (p *kAgentChatServiceClient) Login(ctx context.Context, req *chat.LoginRequest, callOptions ...callopt.Option) (r *chat.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kAgentChatServiceClient) Chat(ctx context.Context, req *chat.ChatRequest, callOptions ...callopt.Option) (r *chat.ChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Chat(ctx, req)
}

func (p *kAgentChatServiceClient) CreateSession(ctx context.Context, req *chat.CreateSessionRequest, callOptions ...callopt.Option) (r *chat.CreateSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSession(ctx, req)
}

func (p *kAgentChatServiceClient) ListSessions(ctx context.Context, req *chat.ListSessionsRequest, callOptions ...callopt.Option) (r *chat.ListSessionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSessions(ctx, req)
}

func (p *kAgentChatServiceClient) GetSession(ctx context.Context, req *chat.GetSessionRequest, callOptions ...callopt.Option) (r *chat.GetSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSession(ctx, req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAgentChatServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAgentChatServiceStreamClient struct {
	*kClient
}

func (p *kAgentChatServiceStreamClient) ChatStream(ctx context.Context, req *chat.ChatRequest, callOptions ...streamcall.Option) (stream AgentChatService_ChatStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.ChatStream(ctx, req)
}
