// Code generated by Kitex v1.15.3. DO NOT EDIT.

package thirdbusinessservice

import (
	third "agnet-project-demo/third/kitex_gen/third"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetUserByName(ctx context.Context, req *third.GetUserByNameRequest, callOptions ...callopt.Option) (r *third.GetUserByNameResponse, err error)
	GetUserByID(ctx context.Context, req *third.GetUserByIDRequest, callOptions ...callopt.Option) (r *third.GetUserByIDResponse, err error)
	ListIMConversations(ctx context.Context, req *third.ListIMConversationsRequest, callOptions ...callopt.Option) (r *third.ListIMConversationsResponse, err error)
	GetIMConversationMessages(ctx context.Context, req *third.GetIMConversationMessagesRequest, callOptions ...callopt.Option) (r *third.GetIMConversationMessagesResponse, err error)
	SendIMMessage(ctx context.Context, req *third.SendIMMessageRequest, callOptions ...callopt.Option) (r *third.SendIMMessageResponse, err error)
	RecommendProducts(ctx context.Context, req *third.RecommendProductsRequest, callOptions ...callopt.Option) (r *third.RecommendProductsResponse, err error)
	CheckFreeSample(ctx context.Context, req *third.CheckFreeSampleRequest, callOptions ...callopt.Option) (r *third.CheckFreeSampleResponse, err error)
	AddSelectionCart(ctx context.Context, req *third.AddSelectionCartRequest, callOptions ...callopt.Option) (r *third.AddSelectionCartResponse, err error)
	GetSelectionCart(ctx context.Context, req *third.GetSelectionCartRequest, callOptions ...callopt.Option) (r *third.GetSelectionCartResponse, err error)
	ApplyFreeSample(ctx context.Context, req *third.ApplyFreeSampleRequest, callOptions ...callopt.Option) (r *third.ApplyFreeSampleResponse, err error)
	BuySample(ctx context.Context, req *third.BuySampleRequest, callOptions ...callopt.Option) (r *third.BuySampleResponse, err error)
	GetFulfillmentStatus(ctx context.Context, req *third.GetFulfillmentStatusRequest, callOptions ...callopt.Option) (r *third.GetFulfillmentStatusResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kThirdBusinessServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kThirdBusinessServiceClient struct {
	*kClient
}

func (p *kThirdBusinessServiceClient) GetUserByName(ctx context.Context, req *third.GetUserByNameRequest, callOptions ...callopt.Option) (r *third.GetUserByNameResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserByName(ctx, req)
}

func (p *kThirdBusinessServiceClient) GetUserByID(ctx context.Context, req *third.GetUserByIDRequest, callOptions ...callopt.Option) (r *third.GetUserByIDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserByID(ctx, req)
}

func (p *kThirdBusinessServiceClient) ListIMConversations(ctx context.Context, req *third.ListIMConversationsRequest, callOptions ...callopt.Option) (r *third.ListIMConversationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListIMConversations(ctx, req)
}

func (p *kThirdBusinessServiceClient) GetIMConversationMessages(ctx context.Context, req *third.GetIMConversationMessagesRequest, callOptions ...callopt.Option) (r *third.GetIMConversationMessagesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetIMConversationMessages(ctx, req)
}

func (p *kThirdBusinessServiceClient) SendIMMessage(ctx context.Context, req *third.SendIMMessageRequest, callOptions ...callopt.Option) (r *third.SendIMMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendIMMessage(ctx, req)
}

func (p *kThirdBusinessServiceClient) RecommendProducts(ctx context.Context, req *third.RecommendProductsRequest, callOptions ...callopt.Option) (r *third.RecommendProductsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecommendProducts(ctx, req)
}

func (p *kThirdBusinessServiceClient) CheckFreeSample(ctx context.Context, req *third.CheckFreeSampleRequest, callOptions ...callopt.Option) (r *third.CheckFreeSampleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckFreeSample(ctx, req)
}

func (p *kThirdBusinessServiceClient) AddSelectionCart(ctx context.Context, req *third.AddSelectionCartRequest, callOptions ...callopt.Option) (r *third.AddSelectionCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddSelectionCart(ctx, req)
}

func (p *kThirdBusinessServiceClient) GetSelectionCart(ctx context.Context, req *third.GetSelectionCartRequest, callOptions ...callopt.Option) (r *third.GetSelectionCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSelectionCart(ctx, req)
}

func (p *kThirdBusinessServiceClient) ApplyFreeSample(ctx context.Context, req *third.ApplyFreeSampleRequest, callOptions ...callopt.Option) (r *third.ApplyFreeSampleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyFreeSample(ctx, req)
}

func (p *kThirdBusinessServiceClient) BuySample(ctx context.Context, req *third.BuySampleRequest, callOptions ...callopt.Option) (r *third.BuySampleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BuySample(ctx, req)
}

func (p *kThirdBusinessServiceClient) GetFulfillmentStatus(ctx context.Context, req *third.GetFulfillmentStatusRequest, callOptions ...callopt.Option) (r *third.GetFulfillmentStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFulfillmentStatus(ctx, req)
}
