// Code generated by Kitex v1.15.3. DO NOT EDIT.

package thirdbusinessservice

import (
	third "agnet-project-demo/third/kitex_gen/third"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetUserByName": kitex.NewMethodInfo(
		getUserByNameHandler,
		newThirdBusinessServiceGetUserByNameArgs,
		newThirdBusinessServiceGetUserByNameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserByID": kitex.NewMethodInfo(
		getUserByIDHandler,
		newThirdBusinessServiceGetUserByIDArgs,
		newThirdBusinessServiceGetUserByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListIMConversations": kitex.NewMethodInfo(
		listIMConversationsHandler,
		newThirdBusinessServiceListIMConversationsArgs,
		newThirdBusinessServiceListIMConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetIMConversationMessages": kitex.NewMethodInfo(
		getIMConversationMessagesHandler,
		newThirdBusinessServiceGetIMConversationMessagesArgs,
		newThirdBusinessServiceGetIMConversationMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendIMMessage": kitex.NewMethodInfo(
		sendIMMessageHandler,
		newThirdBusinessServiceSendIMMessageArgs,
		newThirdBusinessServiceSendIMMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecommendProducts": kitex.NewMethodInfo(
		recommendProductsHandler,
		newThirdBusinessServiceRecommendProductsArgs,
		newThirdBusinessServiceRecommendProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckFreeSample": kitex.NewMethodInfo(
		checkFreeSampleHandler,
		newThirdBusinessServiceCheckFreeSampleArgs,
		newThirdBusinessServiceCheckFreeSampleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddSelectionCart": kitex.NewMethodInfo(
		addSelectionCartHandler,
		newThirdBusinessServiceAddSelectionCartArgs,
		newThirdBusinessServiceAddSelectionCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSelectionCart": kitex.NewMethodInfo(
		getSelectionCartHandler,
		newThirdBusinessServiceGetSelectionCartArgs,
		newThirdBusinessServiceGetSelectionCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyFreeSample": kitex.NewMethodInfo(
		applyFreeSampleHandler,
		newThirdBusinessServiceApplyFreeSampleArgs,
		newThirdBusinessServiceApplyFreeSampleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BuySample": kitex.NewMethodInfo(
		buySampleHandler,
		newThirdBusinessServiceBuySampleArgs,
		newThirdBusinessServiceBuySampleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFulfillmentStatus": kitex.NewMethodInfo(
		getFulfillmentStatusHandler,
		newThirdBusinessServiceGetFulfillmentStatusArgs,
		newThirdBusinessServiceGetFulfillmentStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	thirdBusinessServiceServiceInfo                = NewServiceInfo()
	thirdBusinessServiceServiceInfoForClient       = NewServiceInfoForClient()
	thirdBusinessServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return thirdBusinessServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return thirdBusinessServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return thirdBusinessServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ThirdBusinessService"
	handlerType := (*third.ThirdBusinessService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "third",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.15.3",
		Extra:           extra,
	}
	return svcInfo
}

func getUserByNameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceGetUserByNameArgs)
	realResult := result.(*third.ThirdBusinessServiceGetUserByNameResult)
	success, err := handler.(third.ThirdBusinessService).GetUserByName(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceGetUserByNameArgs() interface{} {
	return third.NewThirdBusinessServiceGetUserByNameArgs()
}

func newThirdBusinessServiceGetUserByNameResult() interface{} {
	return third.NewThirdBusinessServiceGetUserByNameResult()
}

func getUserByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceGetUserByIDArgs)
	realResult := result.(*third.ThirdBusinessServiceGetUserByIDResult)
	success, err := handler.(third.ThirdBusinessService).GetUserByID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceGetUserByIDArgs() interface{} {
	return third.NewThirdBusinessServiceGetUserByIDArgs()
}

func newThirdBusinessServiceGetUserByIDResult() interface{} {
	return third.NewThirdBusinessServiceGetUserByIDResult()
}

func listIMConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceListIMConversationsArgs)
	realResult := result.(*third.ThirdBusinessServiceListIMConversationsResult)
	success, err := handler.(third.ThirdBusinessService).ListIMConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceListIMConversationsArgs() interface{} {
	return third.NewThirdBusinessServiceListIMConversationsArgs()
}

func newThirdBusinessServiceListIMConversationsResult() interface{} {
	return third.NewThirdBusinessServiceListIMConversationsResult()
}

func getIMConversationMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceGetIMConversationMessagesArgs)
	realResult := result.(*third.ThirdBusinessServiceGetIMConversationMessagesResult)
	success, err := handler.(third.ThirdBusinessService).GetIMConversationMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceGetIMConversationMessagesArgs() interface{} {
	return third.NewThirdBusinessServiceGetIMConversationMessagesArgs()
}

func newThirdBusinessServiceGetIMConversationMessagesResult() interface{} {
	return third.NewThirdBusinessServiceGetIMConversationMessagesResult()
}

func sendIMMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceSendIMMessageArgs)
	realResult := result.(*third.ThirdBusinessServiceSendIMMessageResult)
	success, err := handler.(third.ThirdBusinessService).SendIMMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceSendIMMessageArgs() interface{} {
	return third.NewThirdBusinessServiceSendIMMessageArgs()
}

func newThirdBusinessServiceSendIMMessageResult() interface{} {
	return third.NewThirdBusinessServiceSendIMMessageResult()
}

func recommendProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceRecommendProductsArgs)
	realResult := result.(*third.ThirdBusinessServiceRecommendProductsResult)
	success, err := handler.(third.ThirdBusinessService).RecommendProducts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceRecommendProductsArgs() interface{} {
	return third.NewThirdBusinessServiceRecommendProductsArgs()
}

func newThirdBusinessServiceRecommendProductsResult() interface{} {
	return third.NewThirdBusinessServiceRecommendProductsResult()
}

func checkFreeSampleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceCheckFreeSampleArgs)
	realResult := result.(*third.ThirdBusinessServiceCheckFreeSampleResult)
	success, err := handler.(third.ThirdBusinessService).CheckFreeSample(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceCheckFreeSampleArgs() interface{} {
	return third.NewThirdBusinessServiceCheckFreeSampleArgs()
}

func newThirdBusinessServiceCheckFreeSampleResult() interface{} {
	return third.NewThirdBusinessServiceCheckFreeSampleResult()
}

func addSelectionCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceAddSelectionCartArgs)
	realResult := result.(*third.ThirdBusinessServiceAddSelectionCartResult)
	success, err := handler.(third.ThirdBusinessService).AddSelectionCart(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceAddSelectionCartArgs() interface{} {
	return third.NewThirdBusinessServiceAddSelectionCartArgs()
}

func newThirdBusinessServiceAddSelectionCartResult() interface{} {
	return third.NewThirdBusinessServiceAddSelectionCartResult()
}

func getSelectionCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceGetSelectionCartArgs)
	realResult := result.(*third.ThirdBusinessServiceGetSelectionCartResult)
	success, err := handler.(third.ThirdBusinessService).GetSelectionCart(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceGetSelectionCartArgs() interface{} {
	return third.NewThirdBusinessServiceGetSelectionCartArgs()
}

func newThirdBusinessServiceGetSelectionCartResult() interface{} {
	return third.NewThirdBusinessServiceGetSelectionCartResult()
}

func applyFreeSampleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceApplyFreeSampleArgs)
	realResult := result.(*third.ThirdBusinessServiceApplyFreeSampleResult)
	success, err := handler.(third.ThirdBusinessService).ApplyFreeSample(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceApplyFreeSampleArgs() interface{} {
	return third.NewThirdBusinessServiceApplyFreeSampleArgs()
}

func newThirdBusinessServiceApplyFreeSampleResult() interface{} {
	return third.NewThirdBusinessServiceApplyFreeSampleResult()
}

func buySampleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceBuySampleArgs)
	realResult := result.(*third.ThirdBusinessServiceBuySampleResult)
	success, err := handler.(third.ThirdBusinessService).BuySample(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceBuySampleArgs() interface{} {
	return third.NewThirdBusinessServiceBuySampleArgs()
}

func newThirdBusinessServiceBuySampleResult() interface{} {
	return third.NewThirdBusinessServiceBuySampleResult()
}

func getFulfillmentStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*third.ThirdBusinessServiceGetFulfillmentStatusArgs)
	realResult := result.(*third.ThirdBusinessServiceGetFulfillmentStatusResult)
	success, err := handler.(third.ThirdBusinessService).GetFulfillmentStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newThirdBusinessServiceGetFulfillmentStatusArgs() interface{} {
	return third.NewThirdBusinessServiceGetFulfillmentStatusArgs()
}

func newThirdBusinessServiceGetFulfillmentStatusResult() interface{} {
	return third.NewThirdBusinessServiceGetFulfillmentStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserByName(ctx context.Context, req *third.GetUserByNameRequest) (r *third.GetUserByNameResponse, err error) {
	var _args third.ThirdBusinessServiceGetUserByNameArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceGetUserByNameResult
	if err = p.c.Call(ctx, "GetUserByName", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserByID(ctx context.Context, req *third.GetUserByIDRequest) (r *third.GetUserByIDResponse, err error) {
	var _args third.ThirdBusinessServiceGetUserByIDArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceGetUserByIDResult
	if err = p.c.Call(ctx, "GetUserByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListIMConversations(ctx context.Context, req *third.ListIMConversationsRequest) (r *third.ListIMConversationsResponse, err error) {
	var _args third.ThirdBusinessServiceListIMConversationsArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceListIMConversationsResult
	if err = p.c.Call(ctx, "ListIMConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetIMConversationMessages(ctx context.Context, req *third.GetIMConversationMessagesRequest) (r *third.GetIMConversationMessagesResponse, err error) {
	var _args third.ThirdBusinessServiceGetIMConversationMessagesArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceGetIMConversationMessagesResult
	if err = p.c.Call(ctx, "GetIMConversationMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendIMMessage(ctx context.Context, req *third.SendIMMessageRequest) (r *third.SendIMMessageResponse, err error) {
	var _args third.ThirdBusinessServiceSendIMMessageArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceSendIMMessageResult
	if err = p.c.Call(ctx, "SendIMMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecommendProducts(ctx context.Context, req *third.RecommendProductsRequest) (r *third.RecommendProductsResponse, err error) {
	var _args third.ThirdBusinessServiceRecommendProductsArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceRecommendProductsResult
	if err = p.c.Call(ctx, "RecommendProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckFreeSample(ctx context.Context, req *third.CheckFreeSampleRequest) (r *third.CheckFreeSampleResponse, err error) {
	var _args third.ThirdBusinessServiceCheckFreeSampleArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceCheckFreeSampleResult
	if err = p.c.Call(ctx, "CheckFreeSample", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddSelectionCart(ctx context.Context, req *third.AddSelectionCartRequest) (r *third.AddSelectionCartResponse, err error) {
	var _args third.ThirdBusinessServiceAddSelectionCartArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceAddSelectionCartResult
	if err = p.c.Call(ctx, "AddSelectionCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSelectionCart(ctx context.Context, req *third.GetSelectionCartRequest) (r *third.GetSelectionCartResponse, err error) {
	var _args third.ThirdBusinessServiceGetSelectionCartArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceGetSelectionCartResult
	if err = p.c.Call(ctx, "GetSelectionCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyFreeSample(ctx context.Context, req *third.ApplyFreeSampleRequest) (r *third.ApplyFreeSampleResponse, err error) {
	var _args third.ThirdBusinessServiceApplyFreeSampleArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceApplyFreeSampleResult
	if err = p.c.Call(ctx, "ApplyFreeSample", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BuySample(ctx context.Context, req *third.BuySampleRequest) (r *third.BuySampleResponse, err error) {
	var _args third.ThirdBusinessServiceBuySampleArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceBuySampleResult
	if err = p.c.Call(ctx, "BuySample", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFulfillmentStatus(ctx context.Context, req *third.GetFulfillmentStatusRequest) (r *third.GetFulfillmentStatusResponse, err error) {
	var _args third.ThirdBusinessServiceGetFulfillmentStatusArgs
	_args.Req = req
	var _result third.ThirdBusinessServiceGetFulfillmentStatusResult
	if err = p.c.Call(ctx, "GetFulfillmentStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
